### ISSUE TITLE
[Enhancement] Plans to enhance 'net' rules with specific hostnames/ips?

### ISSUE THREAD

**Issue by j1warren** [willfindlay/bpfbox#33]
Do you have any plans to enhance bpfbox network rules with specifying hostnames/ips allowed to connect to, as Windows firewalls/HIPS do?
Or is it out of scope of this project?

**Comment by willfindlay** [comment]
This would certainly be possible. We would just need to change the semantics of the network policy keys and then update the policy language accordingly. The tricky part is how to handle things like globbing on IP addresses. There are special BPF map types for this but it's not clear how to do it with a hashmap where the IP is just one component of the key.

In the short term, I think I would like to revisit the way the policy language works before committing to adding any new features.
